[local]
localhost 

[mongodb]
mongodb-dev.solohunting.online

[catalogue]
catalogue-dev.solohunting.online

[redis]
redis-dev.solohunting.online

[user]
user-dev.solohunting.online

[cart]
cart-dev.solohunting.online

[mysql]
mysql-dev.solohunting.online

[shipping]
shipping-dev.solohunting.online

[rabbitmq]
rabbitmq-dev.solohunting.online

[payment]
payment-dev.solohunting.online

[frontend]
frontend-dev.solohunting.online
